import '@/styles/globals.css';

// eslint-disable-next-line camelcase
import { Plus_Jakarta_Sans } from 'next/font/google';
import localFont from 'next/font/local';
import { Providers } from './providers';

// TODO: Get correct font weight for ethereal
const ethereal = localFont({
  variable: '--font-ethereal',
  src: '../../public/ethereal.otf',
});

// TODO: Add metadata
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const sans = Plus_Jakarta_Sans({ subsets: ['latin'], variable: '--font-sans' });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${sans.variable} ${ethereal.variable}`}
    >
      <body className="transition duration-500 dark:bg-[#171717] bg-[#ffffff]">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
